name: CI
on: [push, pull_request]
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win32
            triplet: x86-windows
            arch: x86
            vcpkgPackages: 'curl faad2 fluidsynth freetype glew libflac libjpeg-turbo libmad libmpeg2 libogg libpng libtheora libvorbis sdl2 sdl2-net zlib'
            useNasm: 'true'
          - platform: x64
            arch: x64
            triplet: x64-windows
            vcpkgPackages: 'curl faad2 fluidsynth freetype glew libflac libjpeg-turbo libmad libmpeg2 libogg libpng libtheora libvorbis sdl2 sdl2-net zlib:x64-windows'
    env:
      CONFIGURATION: Release
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
        if: ${{ matrix.useNasm }} == 'true'
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          vcpkgGitCommitId: 0bf3923f9fab4001c00f0f429682a0853b5749e0
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
      - name: Build create_project
        run: |
          cd devtools/create_project/cmake
          cmake .
          cmake --build . -j 2
          ls
          cd ../../../
      - name: Call create_project
        run: |
          mkdir build-residualvm
          cd build-residualvm
          ../devtools/create_project/cmake/Debug/create_project.exe .. --msvc --enable-all-engines ${{ matrix.configflags }}
          ls
      - name: set RESIDUALVM_LIBS env variable
        run: |
          echo "RESIDUALVM_LIBS=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}\\installed\\${{ matrix.triplet }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build residualvm
        run: |
          cd build-residualvm
          ls
          msbuild residualvm.sln /m /p:BuildInParallel=true /p:Configuration=Release /p:PreferredToolArchitecture=x64 /p:Platform=${{ matrix.platform }}
          ls
      - name: Upload residualvm release
        uses: actions/upload-artifact@v2
        with:
          name: residualvm-${{ matrix.arch }}
          path: build-residualvm/**/*.exe
      - name: Upload residualvm libs
        uses: actions/upload-artifact@v2
        with:
          name: residualvm-${{ matrix.arch }}
          path: ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}\\installed\\${{ matrix.triplet }}\\bin\\*.dll
